--- 
   
  gather_facts: false 

- name: Using user_principal_name
  hosts: all
  task:
    - name: List Role Definitions 
      azure.azcollection.azure_rm_aduser_info:
        user_principal_name: "{{ user }}" 
        tenant: "{{ tenant }}" 