--- 
- name: List Role Definitions 
  hosts: localhost  
  gather_facts: false 

- name: Using user_principal_name
  azure.azcollection.azure_rm_aduser_info:
    user_principal_name: "{{ user }}" 
    tenant: "{{ tenant }}" 